//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mark()
        {
            this.JudgeBoothMarks = new HashSet<JudgeBoothMark>();
        }
    
        public int MarkId { get; set; }
        public int ANovelty { get; set; }
        public int ACreativity { get; set; }
        public int AReflects { get; set; }
        public int BOptimal { get; set; }
        public int BContribution { get; set; }
        public int CPosterOral { get; set; }
        public int CDesignDisplay { get; set; }
        public int DTargetMarket { get; set; }
        public int DCompetitiveness { get; set; }
        public double TotalMarks { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JudgeBoothMark> JudgeBoothMarks { get; set; }
    }
}
