//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudgeApps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JudgeAppsModel : DbContext
    {
        public JudgeAppsModel()
            : base("name=JudgeAppsModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Booth> Booths { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<JudgeBoothMark> JudgeBoothMarks { get; set; }
        public virtual DbSet<Judge> Judges { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
    }
}
